wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      4: 3.6.12
      5: 0.10.14
arch:
  desc: null
  value: hybrid
batch_size:
  desc: null
  value: 32
beam_size:
  desc: null
  value: 5
bidirectional:
  desc: null
  value: 0
checkpoint_dir:
  desc: null
  value: tasks/R2R/checkpoints/pano-seq2seq/
depth_feat_dir:
  desc: null
  value: preprocessed_data/depth_result
entropy_weight:
  desc: null
  value: 0.0
epochs_data_augmentation:
  desc: null
  value: 5
eval_beam:
  desc: null
  value: 0
eval_every_epochs:
  desc: null
  value: 5
eval_only:
  desc: null
  value: 0
exp_name:
  desc: null
  value: hybrid-agent-1
exp_name_secondary:
  desc: null
  value: ''
feedback:
  desc: null
  value: argmax
feedback_training:
  desc: null
  value: sample
fix_action_ended:
  desc: null
  value: 1
follow_gt_traj:
  desc: null
  value: 0
img_dropout:
  desc: null
  value: 0.5
img_fc_dim:
  desc: null
  value:
  - 1024
img_fc_use_angle:
  desc: null
  value: 0
img_fc_use_batchnorm:
  desc: null
  value: 1
img_feat_dir:
  desc: null
  value: preprocessed_data/img_features/ResNet-152-imagenet.tsv
img_feat_input_dim:
  desc: null
  value: 2048
lang_embed:
  desc: null
  value: lstm
learning_rate:
  desc: null
  value: 0.0001
log_dir:
  desc: null
  value: tensorboard_logs/pano-seq2seq
max_cap_length:
  desc: null
  value: 100
max_episode_len:
  desc: null
  value: 10
max_navigable:
  desc: null
  value: 36
max_num_epochs:
  desc: null
  value: 300
min_lr:
  desc: null
  value: 1.0e-06
mlp_relu:
  desc: null
  value: 1
model_state:
  desc: null
  value: 1
monitor_sigmoid:
  desc: null
  value: 0
mse_sum:
  desc: null
  value: 1
norm_value:
  desc: null
  value: 0
num_navigable_feat_dir:
  desc: null
  value: preprocessed_data/navigable_result
obj_feat_dir:
  desc: null
  value: preprocessed_data/obj_detection_result
patience:
  desc: null
  value: 3
progress_inference:
  desc: null
  value: 0
remove_punctuation:
  desc: null
  value: 1
results_dir:
  desc: null
  value: tasks/R2R/results/
resume:
  desc: null
  value: ''
reversed:
  desc: null
  value: 0
rnn_dropout:
  desc: null
  value: 0.5
rnn_hidden_size:
  desc: null
  value: 512
rnn_num_layers:
  desc: null
  value: 1
seed:
  desc: null
  value: 1
start_epoch:
  desc: null
  value: 1
teleporting:
  desc: null
  value: 1
tensorboard:
  desc: null
  value: 1
test_submission:
  desc: null
  value: 0
train_data_augmentation:
  desc: null
  value: 0
train_iters_epoch:
  desc: null
  value: 200
train_vocab:
  desc: null
  value: tasks/R2R/data/train_vocab.txt
trainval_vocab:
  desc: null
  value: tasks/R2R/data/trainval_vocab.txt
use_ignore_index:
  desc: null
  value: 1
value_loss_weight:
  desc: null
  value: 0.5
wandbId:
  desc: null
  value: 92jvz2jx
wandb_visualize:
  desc: null
  value: 0
word_embedding_size:
  desc: null
  value: 256
