wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
    t:
      1:
      - 1
      2:
      - 1
      4: 3.6.12
      5: 0.10.14
batch_size:
  desc: null
  value: 32
epochs_data_augmentation:
  desc: null
  value: 5
exp_name:
  desc: null
  value: hybrid-agent
learning_rate:
  desc: null
  value: 0.0001
max_episode_len:
  desc: null
  value: 10
model:
  desc: null
  value: hybrid
resume:
  desc: null
  value: ''
train_data_augmentation:
  desc: null
  value: 0
train_iters_epoch:
  desc: null
  value: 200
